#!/usr/bin/env perl

use strict;
use warnings;

# Match the regex on the command line and print out what is matched,
# including captures

my $Regex = qr/$ARGV[0]/;

while(my $line = <STDIN>) {
  my @extractions = $line =~ m/$Regex/gx;
  my $count = 0;
  for my $extraction (@extractions) {
    print sprintf("%d)%s ", $count, $extraction);
    $count++;
  }
  print "\n";
}
