#!/usr/bin/env perl

use strict;
use warnings;

$|= 1;

my $ENCODED_PATTERN=qr/[%]([0-9A-Fa-f]{2})/;

sub decode
{
  my ($encoded) = @_;
  return chr(hex($encoded));
}

print STDERR "waiting for input on standard in...\n";

while(my $line=<>) {
  $line =~ s/($ENCODED_PATTERN)/&decode($2)/gxe;
  print $line;
}
