"""
Django settings for planets project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR="/app"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q#nn2dki-(d+2qt(02fx$n#q+#ml%s#*o$c4ask=9j5bc^38s1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'page.apps.PageConfig',
    'planetor.apps.PlanetorConfig',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'planets.urls'

CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'planets.wsgi.application'
# APPEND_SLASH=False

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# SQLite3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR + '/' + 'db.sqlite3',
    }
}

#PSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'planeteerdb',
#         'USER': 'patrickskelley',
#         'PASSWORD': 'psqlmousedarkknight',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'planets/static'),
# ]

# Note can be in a separate dir on server

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT_1 = os.path.join(BASE_DIR, 'planetor/out/gallery')
MEDIA_ROOT_2 = os.path.join(BASE_DIR, 'planetor/out/stills')
MEDIA_ROOT_3 = os.path.join(BASE_DIR, 'planetor/out/editspecs')
MEDIA_ROOT_4 = os.path.join(BASE_DIR, 'planetor/out/lifeforms')
MEDIA_ROOT_5 = os.path.join(BASE_DIR, 'planetor/out/logs')
MOBILE_ROOT = os.path.join(BASE_DIR, 'mobile')
WEBSITE_ROOT = os.path.join(BASE_DIR, 'website')
GAME_ROOT = os.path.join(BASE_DIR, 'game')
DOCUMENTATION_ROOT = os.path.join(BASE_DIR, 'documentation')
FONTS = os.path.join(BASE_DIR, 'planetor/fonts/')

MEDIA_URL = '/media/'
MEDIA_URL_1 = '/gallery/'
MEDIA_URL_2 = '/stills/'
MEDIA_URL_3 = '/editspecs/'
MEDIA_URL_4 = '/lifeforms/'
MEDIA_URL_5 = '/logs/'
MOBILE_URL = '/m/'
WEBSITE_URL= '/website/'
GAME_URL= '/g/'
DOCUMENTATION_URL = '/dox/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Variables from local_settings will overwrite settings above. local_settings.py is stored on the server
try:
    from .local_settings import *
except ImportError:
    pass

